/**
 * Reads STORMIC_SIGNAL_URL from client/.env and writes it into
 * src/renderer/signal-url.js so it is baked into the packaged build.
 *
 * Run automatically by npm start / build scripts.
 * The generated file is gitignored — the URL never ends up in the repo.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const root      = path.join(__dirname, '..');
const envFile   = path.join(root, '.env');
const outFile   = path.join(root, 'src', 'renderer', 'signal-url.js');

let signalUrl = '';

if (fs.existsSync(envFile)) {
  const lines = fs.readFileSync(envFile, 'utf-8').split('\n');
  for (const line of lines) {
    const m = line.match(/^\s*STORMIC_SIGNAL_URL\s*=\s*(.+?)\s*$/);
    if (m) {
      signalUrl = m[1].replace(/^["']|["']$/g, '');
      break;
    }
  }
}

if (signalUrl) {
  console.log('[stormic] Signal URL loaded from .env');
} else {
  console.log('[stormic] No STORMIC_SIGNAL_URL in .env — URL must be set in app settings');
}

fs.writeFileSync(
  outFile,
  `// Auto-generated by scripts/generate-env.js — DO NOT EDIT, DO NOT COMMIT\nwindow.__STORMIC_SIGNAL_URL__ = ${JSON.stringify(signalUrl)};\n`,
);
